repos:
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.14
    hooks:
      - id: ruff