[build-system]
build-backend = 'setuptools.build_meta'
requires = ["setuptools >= 62.0"]

[project]
name = "pyCANape"
description = 'Pythonic wrapper around the VECTOR CANape API'
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
keywords = [
    "CANape",
    "Measurement",
    "Calibration",
    "automotive"
]
authors = [
  { name = "Artur Drogunow", email = "artur.drogunow@zf.com" },
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "psutil",
    "numpy",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "black==22.8.*",
    "sphinx==5.2.*",
    "build",
    "twine",
]
doc = [
    "furo",
    "sphinx==5.2.*",
]

[project.urls]
Documentation = "https://pycanape.readthedocs.io"
Issues = "https://github.com/zariiii9003/pycanape/issues"
Source = "https://github.com/zariiii9003/pycanape"
Homepage = "https://github.com/zariiii9003/pycanape"

[tool.setuptools.dynamic]
version = {attr = "pycanape.__version__"}

[tool.black]
exclude = '''
/(
  | .venv
  | venv
  | .tox
  | build
  | dist
  | .mypy_cache
  | .pytest_cache
)/
'''
